### ISSUE TITLE
Update spago's `run` command

### ISSUE THREAD

**Issue by i-am-the-slime** [working-group-purescript-es/spago#1]
`spago run` currently depends on a file that `require`s `Main`, however this leads to the following error:

```
require('/Users/mark/code/working-group-purescript-es.github.io/output/Main').main()
^

Error [ERR_REQUIRE_ESM]: require() of ES Module ./output/Main/index.js from ./.spago/run.js not supported.
Instead change the require of index.js in ./.spago/run.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (..spago/run.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.2.0
```

The file `./.spago/run.js` currently looks like this:

```
#!/usr/bin/env node

require('/Users/mark/code/working-group-purescript-es.github.io/output/Main').main()
```

The following replacement works as long as its filename ends in `.mjs`:

```
import { main } from "/Users/mark/code/working-group-purescript-es.github.io/output/Main/index.js"
main();
```

Note that it's required to specifically specify `/index.js` at the end.

**Comment by JordanMartinez** [comment]
Per [Node 14 docs](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_enabling):
> Node.js treats JavaScript code as CommonJS modules by default. Authors can tell Node.js to treat JavaScript code as ECMAScript modules via the `.mjs` file extension, the `package.json` "type" field, or the `--input-type` flag. See [Modules: Packages](https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_input_type_flag) for more details.

The `--input-type` is only for `node --eval` or inputs from `stdin`. Is there a reason why Spago creates a `run.js` file in the first place?

**Comment by JordanMartinez** [comment]
For example, this works:
```sh
$ spago build
$ node --input-type=module --eval "import * as Main from \"./output/Main/index.js\"; Main.main();"
🍝
```

**Comment by sigma-andex** [comment]
I have updated the current branch with this proposal. We can close this issue now I think
